# Use latest stable Debian slim image as base
FROM debian:stable-slim

ARG NVM_VERSION="0.40.3" \
    # Defaults to latest stable Node.js version
    NODE_VERSION="lts/*" \
    # Defaults to latest stable Python version
    PYTHON_VERSIONS=""

# Prevent interactive prompts during apt package installation
ENV DEBIAN_FRONTEND="noninteractive"

# Install essential tools
RUN apt-get update && apt-get -y install --no-install-recommends \
    curl \
    wget \
    git \
    zsh \
    ca-certificates \
    openssh-client \
    # Clean up apt cache
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    # Set zsh as the default shell for root user
    && chsh -s /bin/zsh root \
    # Install Oh My Zsh and plugins
    && sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended \
    && git clone --depth=1 https://github.com/romkatv/powerlevel10k.git "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k" \
    && git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions \
    && git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting \
    # Install Node Version Manager (nvm), initialize nvm, and install selected Node.js version
    && curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v${NVM_VERSION}/install.sh | bash \
    && bash -c "source $HOME/.nvm/nvm.sh && nvm install $NODE_VERSION" \
    # Install uv, source uv environment variables, and install Python version(s)
    && curl -LsSf https://astral.sh/uv/install.sh | sh \
    && . $HOME/.local/bin/env && uv python install ${PYTHON_VERSIONS}

# Load custom zsh and p10k configuration
COPY ./shell-config/.zshrc /root/.zshrc
COPY ./shell-config/p10k.zsh /root/.p10k.zsh